const $=s=>document.querySelector(s);let state={user:null,view:'dashboard'};
const SUBJECTS=['Elektrotexnika','Elektronika','Raqamli qurilmalar','Avtomatika asoslari','Kompyuter tarmoqlari','Mikroprotsessor texnikasi','Axborot tizimlari','Dasturlash asoslari','Maʼlumotlar bazasi','Kiberxavfsizlik','Sanoat robototexnikasi','Mexatronika','Energetika tizimlari','Signal va tizimlar','Telekommunikatsiya','IoT texnologiyalari','Sunʼiy intellekt asoslari','Web texnologiyalar','Operatsion tizimlar','Bulutli texnologiyalar','CAD/CAM tizimlari','Texnik chizmachilik','Metrologiya','Materialshunoslik','Mexanika','Gidravlika','Issiqlik texnikasi','Elektr mashinalari','Boshqaruv tizimlari','Kasbiy pedagogika'];
function makeData(){const teachers=Array.from({length:30},(_,i)=>({id:i+1,name:`O‘qituvchi ${i+1}`,login:`teacher${i+1}`,password:'teacher123',role:'teacher',subject:SUBJECTS[i]}));const students=Array.from({length:30},(_,i)=>({id:i+1,name:`Talaba ${i+1}`,login:`student${i+1}`,password:'student123',role:'student',group:`VL-${String(Math.floor(i/10)+1).padStart(2,'0')}`}));const subjects=SUBJECTS.map((s,i)=>({id:i+1,name:s,teacher:teachers[i].name,labs:3,tests:30}));return {teachers,students,subjects,results:[],reports:[],logs:[]}}
let db=JSON.parse(localStorage.getItem('vl_db')||'null')||makeData();function save(){localStorage.setItem('vl_db',JSON.stringify(db))}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
const users=()=>[{name:'Administrator',login:'admin',password:'admin123',role:'admin'},...db.teachers,...db.students];
$('#togglePassword').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#togglePassword').textContent=p.type==='password'?'Ko‘rsatish':'Yashirish'};
$('#loginForm').onsubmit=e=>{e.preventDefault();const u=users().find(x=>x.login===$('#username').value.trim()&&x.password===$('#password').value.trim());if(!u)return toast('Login yoki parol noto‘g‘ri');state.user=u;$('#loginPage').classList.add('hidden');$('#appPage').classList.remove('hidden');render()};
$('#logoutBtn').onclick=()=>{state.user=null;$('#appPage').classList.add('hidden');$('#loginPage').classList.remove('hidden');$('#password').value='';};
function menuItems(){let r=state.user.role;let all={dashboard:'Dashboard',subjects:'Fanlar',labs:'Laboratoriya',tests:'Testlar',results:'Natijalar',users:'Foydalanuvchilar',reports:'Hisobotlar',monitoring:'Monitoring'};let keys=r==='admin'?['dashboard','users','subjects','results','monitoring']:r==='teacher'?['dashboard','subjects','labs','tests','reports','results','monitoring']:['dashboard','subjects','labs','tests','results'];return keys.map(k=>`<button class="nav-btn ${state.view===k?'active':''}" onclick="go('${k}')">${all[k]}</button>`).join('')}
function go(v){state.view=v;render()}window.go=go;
function render(){if(!state.user)return;$('#menu').innerHTML=menuItems();$('#currentUserName').textContent=state.user.name;$('#currentUserRole').textContent=roleName(state.user.role);$('#userAvatar').textContent=state.user.name[0];let titles={dashboard:'Dashboard',subjects:'Fanlar katalogi',labs:'Virtual laboratoriya',tests:'Test nazorati',results:'Natijalar',users:'Foydalanuvchilar',reports:'Hisobotlar',monitoring:'Monitoring'};$('#pageTitle').textContent=titles[state.view];$('#pageSubTitle').textContent='Virtual laboratoriya boshqaruv tizimi';({dashboard,subjects,labs,tests,results,usersView,reports,monitoring}[state.view==='users'?'usersView':state.view])()}
function roleName(r){return r==='admin'?'Administrator':r==='teacher'?'O‘qituvchi':'Talaba'}
function dashboard(){let html=`<div class="stats"><div class="stat"><b>${db.students.length}</b><span>Talabalar</span></div><div class="stat"><b>${db.teachers.length}</b><span>O‘qituvchilar</span></div><div class="stat"><b>${db.subjects.length}</b><span>Fanlar</span></div><div class="stat"><b>${db.subjects.reduce((a,b)=>a+b.tests,0)}</b><span>Test savollari</span></div></div><div class="grid"><div class="card"><h3>Platforma maqsadi</h3><p>Texnik fanlarda virtual laboratoriya, raqamli simulyatsiya, avtomatik baholash va monitoringni birlashtirish.</p></div><div class="card"><h3>Modullar</h3><p>Autentifikatsiya, fanlar, laboratoriya ishlari, testlar, hisobotlar, baholash, monitoring va administrator paneli.</p></div><div class="card"><h3>GitHub Pages</h3><p>Loyiha backend talab qilmaydi. index.html, style.css va app.js fayllarini repositoryga yuklasangiz ishlaydi.</p></div></div>`;$('#content').innerHTML=html}
function subjects(){let list=db.subjects.map(s=>`<tr><td>${s.id}</td><td><b>${s.name}</b></td><td>${s.teacher}</td><td>${s.labs} ta</td><td><span class="badge">${s.tests} ta test</span></td></tr>`).join('');$('#content').innerHTML=`<div class="toolbar"><input class="search" placeholder="Fan qidirish..." oninput="filterTable(this.value)"></div><div class="table-wrap"><table id="dataTable"><thead><tr><th>ID</th><th>Fan</th><th>O‘qituvchi</th><th>Laboratoriya</th><th>Test</th></tr></thead><tbody>${list}</tbody></table></div>`}
function usersView(){let st=db.students.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.login}</td><td>${x.group}</td><td><span class="badge ok">Talaba</span></td></tr>`).join('');let tc=db.teachers.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.login}</td><td>${x.subject}</td><td><span class="badge">O‘qituvchi</span></td></tr>`).join('');$('#content').innerHTML=`<div class="toolbar"><input class="search" placeholder="Foydalanuvchi qidirish..." oninput="filterTable(this.value)"><button class="small-btn" onclick="resetData()">30/30/30 qayta tiklash</button></div><div class="table-wrap"><table id="dataTable"><thead><tr><th>ID</th><th>F.I.O</th><th>Login</th><th>Guruh/Fan</th><th>Rol</th></tr></thead><tbody>${tc+st}</tbody></table></div>`}
function labs(){let subjectOptions=db.subjects.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#content').innerHTML=`<div class="lab-shell"><div class="panel"><h3>Interaktiv tajriba</h3><label>Fan</label><select id="labSubject">${subjectOptions}</select><div class="range-row"><label>R qarshilik (Ω)</label><input id="rVal" type="number" value="50"></div><div class="range-row"><label>U kuchlanish (V)</label><input id="uVal" type="number" value="12"></div><div class="range-row"><label>f chastota (Hz)</label><input id="fVal" type="number" value="50"></div><button class="primary-btn" onclick="runLab()">Tajribani bajarish</button><p id="labInfo"></p></div><div class="panel"><h3>Natija va grafik tahlil</h3><div class="canvas-box"><canvas id="chart" width="900" height="280"></canvas></div><div id="labTable" class="table-wrap" style="margin-top:14px"></div></div></div>`;runLab()}
function runLab(){let r=+$('#rVal').value,u=+$('#uVal').value,f=+$('#fVal').value;if(r<=0||u<=0||f<=0)return toast('Qiymatlar musbat bo‘lishi kerak');let current=(u/r).toFixed(3),power=(u*current).toFixed(2),score=Math.min(100,Math.round(60+current*80));let subject=db.subjects.find(s=>s.id===$('#labSubject').value*1);let rec={date:new Date().toLocaleString('uz-UZ'),student:state.user.name,subject:subject.name,current,power,score};db.results.push(rec);db.logs.push({user:state.user.name,action:`${subject.name} bo‘yicha tajriba bajardi`,date:rec.date});save();$('#labInfo').innerHTML=`<b>Hisob:</b> I = U/R = ${current} A, P = ${power} W. Avtomatik ball: <b>${score}</b>`;$('#labTable').innerHTML=`<table><thead><tr><th>Parametr</th><th>Qiymat</th></tr></thead><tbody><tr><td>Kuchlanish</td><td>${u} V</td></tr><tr><td>Qarshilik</td><td>${r} Ω</td></tr><tr><td>Chastota</td><td>${f} Hz</td></tr><tr><td>Tok</td><td>${current} A</td></tr><tr><td>Quvvat</td><td>${power} W</td></tr></tbody></table>`;drawChart(u,r)}window.runLab=runLab;
function drawChart(u,r){let c=$('#chart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#cbd5e1';ctx.lineWidth=1;for(let i=0;i<8;i++){let y=25+i*30;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(860,y);ctx.stroke()}ctx.strokeStyle='#2563eb';ctx.lineWidth=4;ctx.beginPath();for(let x=0;x<=800;x+=40){let volt=x/800*u*2;let amp=volt/r;let px=45+x,py=245-amp*900;if(x===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.stroke();ctx.fillStyle='#14213d';ctx.font='18px Arial';ctx.fillText('Tok-kuchlanish bog‘lanishi grafigi',40,22);ctx.font='13px Arial';ctx.fillText('U (V)',820,265);ctx.fillText('I (A)',8,48)}
function tests(){let qs=Array.from({length:30},(_,i)=>({q:`${i+1}. Virtual laboratoriyada baholashning asosiy maqsadi nima?`,a:['Natijani avtomatik va shaffof baholash','Faqat rasm ko‘rsatish','Loginni o‘chirish','Fanni yashirish'],c:0}));$('#content').innerHTML=`<div class="card"><h3>30 ta test savoli</h3><div id="quiz">${qs.map((q,i)=>`<div class="test-block"><b>${q.q}</b>${q.a.map((a,j)=>`<label class="test-option"><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('')}</div><button class="primary-btn" onclick="finishTest()">Testni yakunlash</button><p id="testResult"></p></div>`}
function finishTest(){let ok=0;for(let i=0;i<30;i++){let v=document.querySelector(`input[name=q${i}]:checked`);if(v&&v.value==='0')ok++}let score=Math.round(ok/30*100);db.results.push({date:new Date().toLocaleString('uz-UZ'),student:state.user.name,subject:'Test nazorati',current:'-',power:'-',score});db.logs.push({user:state.user.name,action:`Test ishladi: ${score} ball`,date:new Date().toLocaleString('uz-UZ')});save();$('#testResult').innerHTML=`Natija: <b>${ok}/30</b>, ball: <b>${score}</b>`}window.finishTest=finishTest;
function results(){let rows=db.results.slice(-80).reverse().map((r,i)=>`<tr><td>${i+1}</td><td>${r.date}</td><td>${r.student}</td><td>${r.subject}</td><td>${r.current}</td><td>${r.power}</td><td><span class="badge ${r.score<60?'danger':'ok'}">${r.score}</span></td></tr>`).join('')||'<tr><td colspan="7">Hali natija yo‘q</td></tr>';$('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>#</th><th>Sana</th><th>Talaba</th><th>Fan/bo‘lim</th><th>Tok</th><th>Quvvat</th><th>Ball</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function reports(){let rows=db.results.slice(-30).reverse().map((r,i)=>`<tr><td>${i+1}</td><td>${r.student}</td><td>${r.subject}</td><td>${r.date}</td><td><span class="badge ok">Qabul qilindi</span></td><td>${r.score}</td></tr>`).join('')||'<tr><td colspan="6">Hisobotlar mavjud emas</td></tr>';$('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>#</th><th>Talaba</th><th>Laboratoriya</th><th>Sana</th><th>Holat</th><th>Ball</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function monitoring(){let rows=db.logs.slice(-100).reverse().map((l,i)=>`<tr><td>${i+1}</td><td>${l.user}</td><td>${l.action}</td><td>${l.date}</td></tr>`).join('')||'<tr><td colspan="4">Monitoring yozuvi yo‘q</td></tr>';$('#content').innerHTML=`<div class="grid"><div class="card"><h3>Faollik statistikasi</h3><p>Talabalar tajriba bajarishi, test ishlashi va natijalari avtomatik qayd etiladi.</p></div><div class="card"><h3>O‘rtacha ball</h3><b style="font-size:42px">${avgScore()}</b></div></div><br><div class="table-wrap"><table><thead><tr><th>#</th><th>Foydalanuvchi</th><th>Harakat</th><th>Sana</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function avgScore(){if(!db.results.length)return 0;return Math.round(db.results.reduce((a,b)=>a+(+b.score||0),0)/db.results.length)}
function filterTable(q){q=q.toLowerCase();document.querySelectorAll('#dataTable tbody tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')}window.filterTable=filterTable;
function resetData(){if(confirm('Maʼlumotlar 30 ta o‘qituvchi, 30 ta talaba va 30 ta fan holatiga qaytarilsinmi?')){db=makeData();save();render();toast('Maʼlumotlar qayta tiklandi')}}window.resetData=resetData;
